service: aws-http-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

plugins:
  - serverless-offline
  - serverless-dynamodb

custom:
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

resources:
  Resources:
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: userTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

  findAllUser:
    handler: src/user/user.findAll
    events:
      - httpApi:
          path: /user
          method: get
  saveUser:
    handler: src/user/user.create
    events:
      - httpApi:
          path: /user
          method: post
